# .github/workflows/update.yml
name: Update Clinics JSON

on:
  schedule:
    - cron: "15 2 */3 * *"   # 每 3 天 UTC 02:15（台北 10:15）
  workflow_dispatch:

concurrency:
  group: update-clinics-json
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build crawler image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: clinics-crawler:latest
          load: true

      - name: Prepare folders
        run: mkdir -p public data out

      - name: Run crawler (same as local)
        env:
          OPENCAGE_API_KEY: ${{ secrets.OPENCAGE_API_KEY }}
          NOMINATIM_USER_AGENT: suihsilan-crawler/1.0
          CI: "1"
        run: |
          set -euo pipefail
          docker run --rm --platform=linux/amd64 \
            --shm-size=1g --ipc=host \
            -e OPENCAGE_API_KEY \
            -e NOMINATIM_USER_AGENT \
            -e CI \
            -v "$GITHUB_WORKSPACE":/app \
            -w /app \
            clinics-crawler:latest \
            bash -lc '\
              mkdir -p out && \
              node src/index.js --out ./out/taiwan_merged_clean.json && \
              node src/geocode-diff-merge.js \
                --clean ./out/taiwan_merged_clean.json \
                --prev  ./public/clinics.json \
                --cache ./data/geocode-cache.json \
                --out   ./public/clinics.json \
                --diff  ./out/new_clinics.json && \
              npm run validate && \
              node scripts/check-total.js public/clinics.json \
            '

      - name: Commit & push changes
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- public/clinics.json out/new_clinics.json; then
            git add public/clinics.json out/new_clinics.json
            git commit -m "chore(ci): update clinics.json and diff [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      # 失敗時上傳除錯檔（你 log 裡看到的 *.png/*.html/fatal.txt）
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crawl-debug
          path: |
            out/*.png
            out/*.html
            out/fatal.txt
            out/taiwan_merged_clean.json
            out/taiwan_merged_clean.csv
